apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth-depl.yaml
  - client-depl.yaml
  - ingress-srv.yaml

configMapGenerator:
  - name: client-config
    envs:
      - .env.client-config

secretGenerator:
  - name: client-secret
    envs:
      - .env.client-secret
  - name: auth-secret
    envs:
      - .env.auth-secret
