apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: app-config
    behavior: merge
    envs:
      - app-config.env

secretGenerator:
  - name: app-secret
    envs:
      - .env.app-secret
