apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: prod

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: ingress-service
    path: ingress-patch.yaml

configMapGenerator:
  - name: client-config
    behavior: merge
    envs:
      - client-config.env
